### ISSUE TITLE
moderngpu stuck in a dead lock on Volta GPU 

### ISSUE THREAD

**Issue by YuxinxinChen** [gunrock/mini#3]
I am trying to run mini Gunrock BFS on daisy which has Volta GPU.
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168

gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

However, it is stuck in a deadlock. We found the code is stuck at moderngpu transform_scan.

If I run the same code on Luigi which has Tesla K40
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Mini Gunrock BFS runs correctly and successfully.

**Comment by yzhwang** [comment]
Thanks for pointing out. This is due to an incorrect setting of mask in the ptx version of shfl_{down,up}_op() macro in moderngpu. I've fixed this:
https://github.com/yzhwang/moderngpu/commit/de1f72c726b5a586cc10296e15c0f576a6d65488
Again, will send a PR to mgpu and when it gets merged in I will ask you to confirm and close this.
(Probably need some time since its holiday in US).

**Comment by yzhwang** [comment]
I switched the submodule and make it point to my fork of moderngpu (where the fix of deadlock has been applied). Please confirm and close this issue.

**Comment by YuxinxinChen** [comment]
problem solved!
